theme: minima
title: Test Title
author: WakiCDXX
email: jenortega0420@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test description

# social links
twitter_username: wackynatics
github_username:  WakiCDXX

show_excerpts: true # set to false to remove excerpts on the homepage
